# This file was generated by GoReleaser. DO NOT EDIT.
cask "da" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "597e75d5e44607a1b66d650ea9bc641fc84470800d1a42ef7b1e38da1e7ff219"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "626b7155604356ee5e310e926bebb6633b312d193a3c99c50993026b2bc61bdb"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f65ccc1282834c930b23e76e83f0708f8dc132840e6f462d6f95058e290fa68"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "b06b1047492d1c8e571a0484ec5b2827c4d4c13e7e4729b560ad5d3bc500a601"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  name "da"
  desc "Manage AI agent configurations across projects"
  homepage "https://github.com/AGOrcha/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
