# This file was generated by GoReleaser. DO NOT EDIT.
cask "da@0.4.0" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "0648b1695550b124232c8aaf44c7377feeccf7d9f9cfb80291b56d411a165ac1"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "019fbd25d0ca656eb9ae2d72fee0f85dffc0756d3bfad6d1f72def340391827b"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a6068d0223bf45645195a5864e8ba5b3789e3acca139e8652ddb071c4be5c8a"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "0cfb71b2b05f6c81fbc75585e835b8e45e6da5a5a47629066a6b9ef1237ff966"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  name "da@0.4.0"
  desc "Manage AI agent configurations across projects (v0.4.0 pinned)"
  homepage "https://github.com/AGOrcha/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
