# This file was generated by GoReleaser. DO NOT EDIT.
cask "da@0.3.4" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "fc5499f4eddb0deb99507aecefb631148a0e9853ca18fa37cafa46eb3c401dfd"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "65385dbc23ce31d93cb868d6a2ca0ba2f207dd6cd28c7fef2dde6d3576a32b9a"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1142db2345ee23ce83fb6c40cf9ba82a3b216da2dd9b99f1c4383db8cd85512d"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "b408507a29ac9a21e78eb887a2d91e9c57a846d690601f5123eee2a921fe4b60"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  name "da@0.3.4"
  desc "Manage AI agent configurations across projects (v0.3.4 pinned)"
  homepage "https://github.com/AGOrcha/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/da"]
    end
  end

  # No zap stanza required

end
