# This file was generated by GoReleaser. DO NOT EDIT.
cask "da@0.4.2" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "4213d55dfb9c00c8181f144c35ec783ca09287e3716c6ee8f5743ccf9360453f"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "4f5314fef42202731070d00c3d96f356a5ba5609bd108bb2725b9339652f366d"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f9d08cad76c7cb4a46dd1175857a112d0d1ae48f3cdfe7591badbc7bb8ee36b"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "71ad0fe2c0f58a0d08b824d2e7056a46cac500247a772993a4c16c187b191950"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  name "da@0.4.2"
  desc "Manage AI agent configurations across projects (v0.4.2 pinned)"
  homepage "https://github.com/AGOrcha/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
