# This file was generated by GoReleaser. DO NOT EDIT.
cask "da@0.5.0" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "5dbe1f1917790bd9dcdfa4568d4f2d4f92581f4e47a51ca28ceedbad1d6d40af"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "12307a4aa577f578fe8b8a5da295ffd8b95f12de149b31cb41c286f9c87cb4c1"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ff465767c8dcb3a421c4b6f60fef51a84d44f79c307f01fb4b42a379c19a13f"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
    on_arm do
      sha256 "c28f1529e974c9ed03c685f34f2d0a7b4e418061cc1b797041575a94b55a2ed1"
      url "https://github.com/AGOrcha/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/AGOrcha/dot-agents/"
    end
  end

  name "da@0.5.0"
  desc "Manage AI agent configurations across projects (v0.5.0 pinned)"
  homepage "https://github.com/AGOrcha/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
