# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-agents" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "7b638345d67e1daf347d9d35fb487e8528b295cf230a2a5a548721b522005e0c"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "9411ef4d40dfdb8656381c8d3eda5b7f9da373c74223c0492c264073587c29a5"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "808f7486bb73295902053c38e4f89278d9f3e4395ebabb77d03000ef539e4c5a"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "cbf5ee274b911517d7b3bef994968152624b91d6857e1e938fc822721a4b3ab6"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  name "dot-agents"
  desc "Manage AI agent configurations across projects"
  homepage "https://github.com/NikashPrakash/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
