# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-agents" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "7ab63ebd7c3e7452d5e7383893c1f557107701a1cfa06a0853f61652a550a8be"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "943e0093ec62cc9db0133072edbded43a0415fb796990a5e1c34f3934777eda5"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "81ddc5a908b56532a7525edd7ffa860f13d4c4623daf75a96d050048017f3b4b"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "6c972db6bcf47a7e31640f871c49f20105ededd83ad87494823c6c295149b204"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  name "dot-agents"
  desc "Manage AI agent configurations across projects"
  homepage "https://github.com/NikashPrakash/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
