# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-agents@0.3.3" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "5f2c6d3f63ef06f235a1f9bcdf540b465b8ddb5a777631cbab5b5c8f06ed48f7"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "eab0bdfe0af505292a1d8994877c0aa32ba82d1729dfb1939b187a677ad22809"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c084120e0fcd538326e012bce7b51969f1d1c4aef73cb4085c83023dad9148a3"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "bdcdb5cc33112865a9bb13b3feac43d85b3ee494adea15db8a97d13cccc47111"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  name "dot-agents@0.3.3"
  desc "Manage AI agent configurations across projects (v0.3.3 pinned)"
  homepage "https://github.com/NikashPrakash/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/da"]
    end
  end

  # No zap stanza required

end
