# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-agents@0.3.3" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "625779245ee6f9856776a59ab5f274fa77f31d8d0f237f3164f9667591e4f854"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "05dcdc40ee256bdee31628226fa70b11c73be481103eea579c41f32d44f9edf2"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1aab1b619cc7cf4d92677fd0d66d306a578d7787a8d90dae518a7938b988bc34"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "c798b1cb01ebd82cb938fe43fd4d8014993ae311abce29287938960bce052084"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  name "dot-agents@0.3.3"
  desc "Manage AI agent configurations across projects (v0.3.3 pinned)"
  homepage "https://github.com/NikashPrakash/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/da"]
    end
  end

  # No zap stanza required

end
