# This file was generated by GoReleaser. DO NOT EDIT.
cask "dot-agents" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "b4b46c73a2bc48a73dcd994b6afc49b7f201761789fd37e83402b7780ff323bf"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "b0675f2d9047698da53550cdb4c4124cc9b48a035da6cebce696e35b72302c4c"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  on_linux do
    on_intel do
      sha256 "de391cee4ccf98abfff6bd86ea00b5c988f4831a331d2bb7d21dc0edbf97a7ea"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_amd64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
    on_arm do
      sha256 "c7bd836ae2924a6f74d6b50a9097e1de5674515d49629aee357bb755fc6536a9"
      url "https://github.com/NikashPrakash/dot-agents/releases/download/v#{version}/dot-agents_#{version}_linux_arm64.tar.gz",
        verified: "github.com/NikashPrakash/dot-agents/"
    end
  end

  name "dot-agents"
  desc "Manage AI agent configurations across projects"
  homepage "https://github.com/NikashPrakash/dot-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "da"

  # No zap stanza required

end
